

import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/landingPage/NavBar/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children
}: Readonly<{children: React.ReactNode}>) {

  return (
    <html lang="es" suppressHydrationWarning>
      <body
        className={` antialiased max-w-[2592px] mx-auto shadow-2xl`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
          >
        <TooltipProvider>
        {children}
        </TooltipProvider>
       </ThemeProvider>
      </body>
    </html>
  );
}