import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children
}: Readonly<{children: React.ReactNode}>) {

  return (
    <html lang="en">
      <body
        className={` antialiased max-w-[2592px] border border-gray-400 mx-auto`}
      >
        <TooltipProvider>
        {children}
        </TooltipProvider>
       
      </body>
    </html>
  );
}